### ISSUE TITLE
Jadeite first task list

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#147]
Here is a task list for the Jadeite July 31st product release: 

- [ ] STON support
- [ ] Jade Test framework with SUnit (Travis CI?)
- [ ] Move JadeServer into Services using STON with tests
- [ ] New Browsers - integrate projects better, extension classes, etc
- [ ] Other tools
- [ ] Refactoring tools

**Comment by dalehenrich** [comment]
I think that this is no longer needed ... https://github.com/GemTalk/Jadeite/projects/1
