### ISSUE TITLE
V2.0 remove obsolete directories, files, and rowan meta data

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#617]
The Rowan checkout has accumulated a fair amount of cruft over the years of development and now that V2.0 is stabilizing, it's a good idea to get rid of the cruft sooner rather than later ... still need to keep 3.5.0 and 3.2.15 functionality of V2.0 but the old deprecated classes and component (1.5) stuff should be swept from the image ... method names need to be revisited but that will be reserved for a separate issue:
- [ ] extra directories
- [ ] no longer relevant scripts and files
- [ ] refactor rowan directory structure to include only the v2.0 artifacts
- [ ] no longer used samples/ files
- [ ] no longer used tests/ directories
- [ ] no longer used tests/ files

**Comment by dalehenrich** [comment]
3.6.0 tests results after d94c840:
```
Rowan STON Cypress Tonel FileSystemGs tests for GemStone '3.6.0'
1349 run, 1306 passed, 24 failed, 19 errors
```
